In [329]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math

In [330]:
train_feat = pd.read_csv(r'training_set_features.csv')
train_label = pd.read_csv(r'training_set_labels.csv')
test_feat = pd.read_csv(r'test_set_features.csv')

In [331]:
train_feat.head()

,respondent_id,h1n1_concern,h1n1_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,...,income_poverty,marital_status,rent_or_own,employment_status,hhs_geo_region,census_msa,household_adults,household_children,employment_industry,employment_occupation
0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,Below Poverty,Not Married,Own,Not in Labor Force,oxchjgsf,Non-MSA,0.0,0.0,NaN,NaN
1,1,3.0,2.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,...,Below Poverty,Not Married,Rent,Employed,bhuqouqj,"MSA, Not Principle City",0.0,0.0,pxcmvdjn,xgwztkwe
2,2,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,"<= $75,000, Above Poverty",Not Married,Own,Employed,qufhixun,"MSA, Not Principle City",2.0,0.0,rucpziij,xtkaffoo
3,3,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,...,Below Poverty,Not Married,Rent,Not in Labor Force,lrircsnp,"MSA, Principle City",0.0,0.0,NaN,NaN
4,4,2.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,...,"<= $75,000, Above Poverty",Married,Own,Employed,qufhixun,"MSA, Not Principle City",1.0,0.0,wxleyezf,emcorrxb

In [332]:
train_label.head()

   respondent_id  h1n1_vaccine  seasonal_vaccine
0              0             0                 0
1              1             0                 1
2              2             0                 0
3              3             0                 1
4              4             0                 0

In [333]:
test_feat.head()

,respondent_id,h1n1_concern,h1n1_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,...,income_poverty,marital_status,rent_or_own,employment_status,hhs_geo_region,census_msa,household_adults,household_children,employment_industry,employment_occupation
0,26707,2.0,2.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,...,"> $75,000",Not Married,Rent,Employed,mlyzmhmf,"MSA, Not Principle City",1.0,0.0,atmlpfrs,hfxkjkmi
1,26708,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,Below Poverty,Not Married,Rent,Employed,bhuqouqj,Non-MSA,3.0,0.0,atmlpfrs,xqwwgdyp
2,26709,2.0,2.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,...,"> $75,000",Married,Own,Employed,lrircsnp,Non-MSA,1.0,0.0,nduyfdeo,pvmttkik
3,26710,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,"<= $75,000, Above Poverty",Married,Own,Not in Labor Force,lrircsnp,"MSA, Not Principle City",1.0,0.0,NaN,NaN
4,26711,3.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,...,"<= $75,000, Above Poverty",Not Married,Own,Employed,lzgpxyit,Non-MSA,0.0,1.0,fcxhlnwr,mxkfnird

In [334]:
train_feat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26707 entries, 0 to 26706
Data columns (total 36 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   respondent_id                26707 non-null  int64
 1   h1n1_concern                 26615 non-null  float64
 2   h1n1_knowledge               26591 non-null  float64
 3   behavioral_antiviral_meds    26636 non-null  float64
 4   behavioral_avoidance         26499 non-null  float64
 5   behavioral_face_mask         26688 non-null  float64
 6   behavioral_wash_hands        26665 non-null  float64
 7   behavioral_large_gatherings  26620 non-null  float64
 8   behavioral_outside_home      26625 non-null  float64
 9   behavioral_touch_face        26579 non-null  float64
 10  doctor_recc_h1n1             24547 non-null  float64
 11  doctor_recc_seasonal         24547 non-null  float64
 12  chronic_med_condition        25736 non-null  float64
 13  child_under_6_months         25887 non-null  float64
 14  health_worker                25903 non-null  float64
 15  health_insurance             14433 non-null  float64
 16  opinion_h1n1_vacc_effective  26316 non-null  float64
 17  opinion_h1n1_risk            26319 non-null  float64
 18  opinion_h1n1_sick_from_vacc  26312 non-null  float64
 19  opinion_seas_vacc_effective  26245 non-null  float64
 20  opinion_seas_risk            26193 non-null  float64
 21  opinion_seas_sick_from_vacc  26170 non-null  float64
 22  age_group                    26707 non-null  object
 23  education                    25300 non-null  object
 24  race                         26707 non-null  object
 25  sex                          26707 non-null  object
 26  income_poverty               22284 non-null  object
 27  marital_status               25299 non-null  object
 28  rent_or_own                  24665 non-null  object
 29  employment_status            25244 non-null  object
 30  hhs_geo_region               26707 non-null  object
 31  census_msa                   26707 non-null  object
 32  household_adults             26458 non-null  float64
 33  household_children           26458 non-null  float64
 34  employment_industry          13377 non-null  object
 35  employment_occupation        13237 non-null  object
dtypes: float64(23), int64(1), object(12)
memory usage: 7.3+ MB

In [335]:
test_feat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26708 entries, 0 to 26707
Data columns (total 36 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   respondent_id                26708 non-null  int64
 1   h1n1_concern                 26623 non-null  float64
 2   h1n1_knowledge               26586 non-null  float64
 3   behavioral_antiviral_meds    26629 non-null  float64
 4   behavioral_avoidance         26495 non-null  float64
 5   behavioral_face_mask         26689 non-null  float64
 6   behavioral_wash_hands        26668 non-null  float64
 7   behavioral_large_gatherings  26636 non-null  float64
 8   behavioral_outside_home      26626 non-null  float64
 9   behavioral_touch_face        26580 non-null  float64
 10  doctor_recc_h1n1             24548 non-null  float64
 11  doctor_recc_seasonal         24548 non-null  float64
 12  chronic_med_condition        25776 non-null  float64
 13  child_under_6_months         25895 non-null  float64
 14  health_worker                25919 non-null  float64
 15  health_insurance             14480 non-null  float64
 16  opinion_h1n1_vacc_effective  26310 non-null  float64
 17  opinion_h1n1_risk            26328 non-null  float64
 18  opinion_h1n1_sick_from_vacc  26333 non-null  float64
 19  opinion_seas_vacc_effective  26256 non-null  float64
 20  opinion_seas_risk            26209 non-null  float64
 21  opinion_seas_sick_from_vacc  26187 non-null  float64
 22  age_group                    26708 non-null  object
 23  education                    25301 non-null  object
 24  race                         26708 non-null  object
 25  sex                          26708 non-null  object
 26  income_poverty               22211 non-null  object
 27  marital_status               25266 non-null  object
 28  rent_or_own                  24672 non-null  object
 29  employment_status            25237 non-null  object
 30  hhs_geo_region               26708 non-null  object
 31  census_msa                   26708 non-null  object
 32  household_adults             26483 non-null  float64
 33  household_children           26483 non-null  float64
 34  employment_industry          13433 non-null  object
 35  employment_occupation        13282 non-null  object
dtypes: float64(23), int64(1), object(12)
memory usage: 7.3+ MB

In [336]:
# Determining what features will be removed bue to the excessive number of NaN values.
# By unsing a threshold of 15% of NaN, the columns 15, 26, 34, 35 have been dropped out.

list_rem_train = train_feat.isnull().sum() > len(train_feat) * 0.15
list_rem_test = test_feat.isnull().sum() > len(test_feat) * 0.15
print(list_rem_train, list_rem_test )

respondent_id                  False
h1n1_concern                   False
h1n1_knowledge                 False
behavioral_antiviral_meds      False
behavioral_avoidance           False
behavioral_face_mask           False
behavioral_wash_hands          False
behavioral_large_gatherings    False
behavioral_outside_home        False
behavioral_touch_face          False
doctor_recc_h1n1               False
doctor_recc_seasonal           False
chronic_med_condition          False
child_under_6_months           False
health_worker                  False
health_insurance                True
opinion_h1n1_vacc_effective    False
opinion_h1n1_risk              False
opinion_h1n1_sick_from_vacc    False
opinion_seas_vacc_effective    False
opinion_seas_risk              False
opinion_seas_sick_from_vacc    False
age_group                      False
education                      False
race                           False
sex                            False
income_poverty                  True
marital_status                 False
rent_or_own                    False
employment_status              False
hhs_geo_region                 False
census_msa                     False
household_adults               False
household_children             False
employment_industry             True
employment_occupation           True
dtype: bool respondent_id                  False
h1n1_concern                   False
h1n1_knowledge                 False
behavioral_antiviral_meds      False
behavioral_avoidance           False
behavioral_face_mask           False
behavioral_wash_hands          False
behavioral_large_gatherings    False
behavioral_outside_home        False
behavioral_touch_face          False
doctor_recc_h1n1               False
doctor_recc_seasonal           False
chronic_med_condition          False
child_under_6_months           False
health_worker                  False
health_insurance                True
opinion_h1n1_vacc_effective    False
opinion_h1n1_risk              False
opinion_h1n1_sick_from_vacc    False
opinion_seas_vacc_effective    False
opinion_seas_risk              False
opinion_seas_sick_from_vacc    False
age_group                      False
education                      False
race                           False
sex                            False
income_poverty                  True
marital_status                 False
rent_or_own                    False
employment_status              False
hhs_geo_region                 False
census_msa                     False
household_adults               False
household_children             False
employment_industry             True
employment_occupation           True
dtype: bool

In [337]:
# Dropping out the features with excessive NaN
feat_rem = ['health_insurance','employment_industry','employment_occupation','income_poverty']
train_feat_rem = train_feat.drop(feat_rem, axis = 1)
test_feat_rem = test_feat.drop(feat_rem, axis = 1)
train_feat_rem.columns, train_feat_rem.shape, test_feat_rem.columns, test_feat_rem.shape

(Index(['respondent_id', 'h1n1_concern', 'h1n1_knowledge',
        'behavioral_antiviral_meds', 'behavioral_avoidance',
        'behavioral_face_mask', 'behavioral_wash_hands',
        'behavioral_large_gatherings', 'behavioral_outside_home',
        'behavioral_touch_face', 'doctor_recc_h1n1', 'doctor_recc_seasonal',
        'chronic_med_condition', 'child_under_6_months', 'health_worker',
        'opinion_h1n1_vacc_effective', 'opinion_h1n1_risk',
        'opinion_h1n1_sick_from_vacc', 'opinion_seas_vacc_effective',
        'opinion_seas_risk', 'opinion_seas_sick_from_vacc', 'age_group',
        'education', 'race', 'sex', 'marital_status', 'rent_or_own',
        'employment_status', 'hhs_geo_region', 'census_msa', 'household_adults',
        'household_children'],
       dtype='object'),
 (26707, 32),
 Index(['respondent_id', 'h1n1_concern', 'h1n1_knowledge',
        'behavioral_antiviral_meds', 'behavioral_avoidance',
        'behavioral_face_mask', 'behavioral_wash_hands',
        'behavioral_large_gatherings', 'behavioral_outside_home',
        'behavioral_touch_face', 'doctor_recc_h1n1', 'doctor_recc_seasonal',
        'chronic_med_condition', 'child_under_6_months', 'health_worker',
        'opinion_h1n1_vacc_effective', 'opinion_h1n1_risk',
        'opinion_h1n1_sick_from_vacc', 'opinion_seas_vacc_effective',
        'opinion_seas_risk', 'opinion_seas_sick_from_vacc', 'age_group',
        'education', 'race', 'sex', 'marital_status', 'rent_or_own',
        'employment_status', 'hhs_geo_region', 'census_msa', 'household_adults',
        'household_children'],
       dtype='object'),
 (26708, 32))

In [338]:
# Checking the new list of columns and their number of NaN
train_feat_rem.isnull().sum()

respondent_id                     0
h1n1_concern                     92
h1n1_knowledge                  116
behavioral_antiviral_meds        71
behavioral_avoidance            208
behavioral_face_mask             19
behavioral_wash_hands            42
behavioral_large_gatherings      87
behavioral_outside_home          82
behavioral_touch_face           128
doctor_recc_h1n1               2160
doctor_recc_seasonal           2160
chronic_med_condition           971
child_under_6_months            820
health_worker                   804
opinion_h1n1_vacc_effective     391
opinion_h1n1_risk               388
opinion_h1n1_sick_from_vacc     395
opinion_seas_vacc_effective     462
opinion_seas_risk               514
opinion_seas_sick_from_vacc     537
age_group                         0
education                      1407
race                              0
sex                               0
marital_status                 1408
rent_or_own                    2042
employment_status              1463
hhs_geo_region                    0
census_msa                        0
household_adults                249
household_children              249
dtype: int64

In [339]:
# Checking the new list of columns and their number of NaN
test_feat_rem.isnull().sum()

respondent_id                     0
h1n1_concern                     85
h1n1_knowledge                  122
behavioral_antiviral_meds        79
behavioral_avoidance            213
behavioral_face_mask             19
behavioral_wash_hands            40
behavioral_large_gatherings      72
behavioral_outside_home          82
behavioral_touch_face           128
doctor_recc_h1n1               2160
doctor_recc_seasonal           2160
chronic_med_condition           932
child_under_6_months            813
health_worker                   789
opinion_h1n1_vacc_effective     398
opinion_h1n1_risk               380
opinion_h1n1_sick_from_vacc     375
opinion_seas_vacc_effective     452
opinion_seas_risk               499
opinion_seas_sick_from_vacc     521
age_group                         0
education                      1407
race                              0
sex                               0
marital_status                 1442
rent_or_own                    2036
employment_status              1471
hhs_geo_region                    0
census_msa                        0
household_adults                225
household_children              225
dtype: int64

In [340]:
# Dropping the rows containing NaN
train_feat_rem.dropna(inplace = True)
train_feat_rem.isnull().sum()

respondent_id                  0
h1n1_concern                   0
h1n1_knowledge                 0
behavioral_antiviral_meds      0
behavioral_avoidance           0
behavioral_face_mask           0
behavioral_wash_hands          0
behavioral_large_gatherings    0
behavioral_outside_home        0
behavioral_touch_face          0
doctor_recc_h1n1               0
doctor_recc_seasonal           0
chronic_med_condition          0
child_under_6_months           0
health_worker                  0
opinion_h1n1_vacc_effective    0
opinion_h1n1_risk              0
opinion_h1n1_sick_from_vacc    0
opinion_seas_vacc_effective    0
opinion_seas_risk              0
opinion_seas_sick_from_vacc    0
age_group                      0
education                      0
race                           0
sex                            0
marital_status                 0
rent_or_own                    0
employment_status              0
hhs_geo_region                 0
census_msa                     0
household_adults               0
household_children             0
dtype: int64

In [341]:
# Dropping the rows containing NaN
test_feat_rem.dropna(inplace = True)
test_feat_rem.isnull().sum()

respondent_id                  0
h1n1_concern                   0
h1n1_knowledge                 0
behavioral_antiviral_meds      0
behavioral_avoidance           0
behavioral_face_mask           0
behavioral_wash_hands          0
behavioral_large_gatherings    0
behavioral_outside_home        0
behavioral_touch_face          0
doctor_recc_h1n1               0
doctor_recc_seasonal           0
chronic_med_condition          0
child_under_6_months           0
health_worker                  0
opinion_h1n1_vacc_effective    0
opinion_h1n1_risk              0
opinion_h1n1_sick_from_vacc    0
opinion_seas_vacc_effective    0
opinion_seas_risk              0
opinion_seas_sick_from_vacc    0
age_group                      0
education                      0
race                           0
sex                            0
marital_status                 0
rent_or_own                    0
employment_status              0
hhs_geo_region                 0
census_msa                     0
household_adults               0
household_children             0
dtype: int64

In [342]:
# Checking if the states in the Train and Test datasets are the same
for ix, column in enumerate (train_feat_rem.iloc[:,1:].columns):
    if sorted(list(test_feat_rem[column].unique())) != sorted(list(train_feat_rem[column].unique())):
        print(ix, column, 'DOES NOT MATCH!')
    else:
        print(ix, column, 'matches')

0 h1n1_concern matches
1 h1n1_knowledge matches
2 behavioral_antiviral_meds matches
3 behavioral_avoidance matches
4 behavioral_face_mask matches
5 behavioral_wash_hands matches
6 behavioral_large_gatherings matches
7 behavioral_outside_home matches
8 behavioral_touch_face matches
9 doctor_recc_h1n1 matches
10 doctor_recc_seasonal matches
11 chronic_med_condition matches
12 child_under_6_months matches
13 health_worker matches
14 opinion_h1n1_vacc_effective matches
15 opinion_h1n1_risk matches
16 opinion_h1n1_sick_from_vacc matches
17 opinion_seas_vacc_effective matches
18 opinion_seas_risk matches
19 opinion_seas_sick_from_vacc matches
20 age_group matches
21 education matches
22 race matches
23 sex matches
24 marital_status matches
25 rent_or_own matches
26 employment_status matches
27 hhs_geo_region matches
28 census_msa matches
29 household_adults matches
30 household_children matches

In [343]:
# Encoding the Categories
from sklearn.preprocessing import OrdinalEncoder
train_obj = []
test_obj = []
for ix,column in enumerate(train_feat_rem.columns):
    if train_feat_rem[column].dtypes == object:
        train_obj.append(column)
        new_column = column + '_code'
        ord_enc = OrdinalEncoder()
        train_feat_rem[new_column] = ord_enc.fit_transform(train_feat_rem[[column]])
        
for ix,column in enumerate(test_feat_rem.columns):
    if test_feat_rem[column].dtypes == object:
        test_obj.append(column)
        new_column = column + '_code'
        ord_enc = OrdinalEncoder()
        test_feat_rem[new_column] = ord_enc.fit_transform(test_feat_rem[[column]])

In [344]:
train_feat_rem

,respondent_id,h1n1_concern,h1n1_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,...,household_children,age_group_code,education_code,race_code,sex_code,marital_status_code,rent_or_own_code,employment_status_code,hhs_geo_region_code,census_msa_code
0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,0.0,3.0,1.0,3.0,0.0,1.0,0.0,1.0,8.0,2.0
1,1,3.0,2.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,...,0.0,1.0,0.0,3.0,1.0,1.0,1.0,0.0,1.0,0.0
3,3,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,...,0.0,4.0,0.0,3.0,0.0,1.0,1.0,1.0,5.0,1.0
4,4,2.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,...,0.0,2.0,3.0,3.0,0.0,0.0,0.0,0.0,9.0,0.0
5,5,3.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,...,3.0,4.0,0.0,3.0,1.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26700,26700,3.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,...,0.0,3.0,0.0,3.0,0.0,0.0,0.0,1.0,6.0,1.0
26701,26701,2.0,2.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,2.0,3.0,0.0,1.0,1.0,1.0,3.0,1.0
26702,26702,2.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,...,0.0,4.0,3.0,3.0,0.0,1.0,0.0,1.0,9.0,2.0
26703,26703,1.0,2.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,2.0,3.0,1.0,1.0,1.0,0.0,6.0,1.0
26706,26706,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,4.0,3.0,3.0,1.0,0.0,0.0,1.0,7.0,1.0

In [345]:
test_obj, train_obj

(['age_group',
  'education',
  'race',
  'sex',
  'marital_status',
  'rent_or_own',
  'employment_status',
  'hhs_geo_region',
  'census_msa'],
 ['age_group',
  'education',
  'race',
  'sex',
  'marital_status',
  'rent_or_own',
  'employment_status',
  'hhs_geo_region',
  'census_msa'])

In [346]:
train_feat_rem.head()

,respondent_id,h1n1_concern,h1n1_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,...,household_children,age_group_code,education_code,race_code,sex_code,marital_status_code,rent_or_own_code,employment_status_code,hhs_geo_region_code,census_msa_code
0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,0.0,3.0,1.0,3.0,0.0,1.0,0.0,1.0,8.0,2.0
1,1,3.0,2.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,...,0.0,1.0,0.0,3.0,1.0,1.0,1.0,0.0,1.0,0.0
3,3,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,...,0.0,4.0,0.0,3.0,0.0,1.0,1.0,1.0,5.0,1.0
4,4,2.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,...,0.0,2.0,3.0,3.0,0.0,0.0,0.0,0.0,9.0,0.0
5,5,3.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,...,3.0,4.0,0.0,3.0,1.0,0.0,0.0,0.0,0.0,1.0

In [347]:
train_feat_rem[['age_group','age_group_code','rent_or_own','rent_or_own_code']]

           age_group  age_group_code rent_or_own  rent_or_own_code
0      55 - 64 Years             3.0         Own               0.0
1      35 - 44 Years             1.0        Rent               1.0
3          65+ Years             4.0        Rent               1.0
4      45 - 54 Years             2.0         Own               0.0
5          65+ Years             4.0         Own               0.0
...              ...             ...         ...               ...
26700  55 - 64 Years             3.0         Own               0.0
26701  18 - 34 Years             0.0        Rent               1.0
26702      65+ Years             4.0         Own               0.0
26703  18 - 34 Years             0.0        Rent               1.0
26706      65+ Years             4.0         Own               0.0

[21710 rows x 4 columns]

In [348]:
train_feat_rem = train_feat_rem.drop(train_obj, axis = 1)
test_feat_rem = test_feat_rem.drop(train_obj, axis = 1)
train_feat_rem.columns, train_feat_rem.shape, test_feat_rem.columns, test_feat_rem.shape

(Index(['respondent_id', 'h1n1_concern', 'h1n1_knowledge',
        'behavioral_antiviral_meds', 'behavioral_avoidance',
        'behavioral_face_mask', 'behavioral_wash_hands',
        'behavioral_large_gatherings', 'behavioral_outside_home',
        'behavioral_touch_face', 'doctor_recc_h1n1', 'doctor_recc_seasonal',
        'chronic_med_condition', 'child_under_6_months', 'health_worker',
        'opinion_h1n1_vacc_effective', 'opinion_h1n1_risk',
        'opinion_h1n1_sick_from_vacc', 'opinion_seas_vacc_effective',
        'opinion_seas_risk', 'opinion_seas_sick_from_vacc', 'household_adults',
        'household_children', 'age_group_code', 'education_code', 'race_code',
        'sex_code', 'marital_status_code', 'rent_or_own_code',
        'employment_status_code', 'hhs_geo_region_code', 'census_msa_code'],
       dtype='object'),
 (21710, 32),
 Index(['respondent_id', 'h1n1_concern', 'h1n1_knowledge',
        'behavioral_antiviral_meds', 'behavioral_avoidance',
        'behavioral_face_mask', 'behavioral_wash_hands',
        'behavioral_large_gatherings', 'behavioral_outside_home',
        'behavioral_touch_face', 'doctor_recc_h1n1', 'doctor_recc_seasonal',
        'chronic_med_condition', 'child_under_6_months', 'health_worker',
        'opinion_h1n1_vacc_effective', 'opinion_h1n1_risk',
        'opinion_h1n1_sick_from_vacc', 'opinion_seas_vacc_effective',
        'opinion_seas_risk', 'opinion_seas_sick_from_vacc', 'household_adults',
        'household_children', 'age_group_code', 'education_code', 'race_code',
        'sex_code', 'marital_status_code', 'rent_or_own_code',
        'employment_status_code', 'hhs_geo_region_code', 'census_msa_code'],
       dtype='object'),
 (21723, 32))

In [349]:
train_feat_rem.head()

,respondent_id,h1n1_concern,h1n1_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,...,household_children,age_group_code,education_code,race_code,sex_code,marital_status_code,rent_or_own_code,employment_status_code,hhs_geo_region_code,census_msa_code
0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,0.0,3.0,1.0,3.0,0.0,1.0,0.0,1.0,8.0,2.0
1,1,3.0,2.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,...,0.0,1.0,0.0,3.0,1.0,1.0,1.0,0.0,1.0,0.0
3,3,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,...,0.0,4.0,0.0,3.0,0.0,1.0,1.0,1.0,5.0,1.0
4,4,2.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,...,0.0,2.0,3.0,3.0,0.0,0.0,0.0,0.0,9.0,0.0
5,5,3.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,...,3.0,4.0,0.0,3.0,1.0,0.0,0.0,0.0,0.0,1.0

In [350]:
train_feat_rem.describe()

,respondent_id,h1n1_concern,h1n1_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,...,household_children,age_group_code,education_code,race_code,sex_code,marital_status_code,rent_or_own_code,employment_status_code,hhs_geo_region_code,census_msa_code
count,21710.000000,21710.000000,21710.000000,21710.000000,21710.000000,21710.000000,21710.000000,21710.000000,21710.000000,21710.000000,...,21710.000000,21710.000000,21710.000000,21710.000000,21710.000000,21710.000000,21710.000000,21710.000000,21710.000000,21710.000000
mean,13358.714325,1.613450,1.289728,0.048503,0.734961,0.067526,0.832381,0.356656,0.334592,0.684892,...,0.531322,2.171764,1.737863,2.581898,0.400368,0.458406,0.238093,0.512437,4.831138,0.834546
std,7707.001900,0.895736,0.603993,0.214832,0.441364,0.250937,0.373536,0.479023,0.471859,0.464570,...,0.925185,1.448400,1.099105,0.912494,0.489984,0.498278,0.425926,0.605308,2.824051,0.825614
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,6703.250000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,...,0.000000,1.000000,1.000000,3.000000,0.000000,0.000000,0.000000,0.000000,3.000000,0.000000
50%,13333.500000,2.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,1.000000,...,0.000000,2.000000,2.000000,3.000000,0.000000,0.000000,0.000000,0.000000,5.000000,1.000000
75%,20042.750000,2.000000,2.000000,0.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,3.000000,3.000000,3.000000,1.000000,1.000000,0.000000,1.000000,7.000000,2.000000
max,26706.000000,3.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,3.000000,4.000000,3.000000,3.000000,1.000000,1.000000,1.000000,2.000000,9.000000,2.000000

### Cleaning and EDA

In [351]:
train_feat_rem.shape, train_label.shape, test_feat_rem.shape

((21710, 32), (26707, 3), (21723, 32))

In [352]:
# Merging Train and Label datasets
train = pd.merge(train_feat_rem, train_label, on = ['respondent_id'])

In [353]:
train

,respondent_id,h1n1_concern,h1n1_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,...,education_code,race_code,sex_code,marital_status_code,rent_or_own_code,employment_status_code,hhs_geo_region_code,census_msa_code,h1n1_vaccine,seasonal_vaccine
0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,1.0,3.0,0.0,1.0,0.0,1.0,8.0,2.0,0,0
1,1,3.0,2.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,...,0.0,3.0,1.0,1.0,1.0,0.0,1.0,0.0,0,1
2,3,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,...,0.0,3.0,0.0,1.0,1.0,1.0,5.0,1.0,0,1
3,4,2.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,...,3.0,3.0,0.0,0.0,0.0,0.0,9.0,0.0,0,0
4,5,3.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,...,0.0,3.0,1.0,0.0,0.0,0.0,0.0,1.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21705,26700,3.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,...,0.0,3.0,0.0,0.0,0.0,1.0,6.0,1.0,0,1
21706,26701,2.0,2.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,...,2.0,3.0,0.0,1.0,1.0,1.0,3.0,1.0,0,0
21707,26702,2.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,...,3.0,3.0,0.0,1.0,0.0,1.0,9.0,2.0,0,0
21708,26703,1.0,2.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,2.0,3.0,1.0,1.0,1.0,0.0,6.0,1.0,0,0
21709,26706,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,3.0,3.0,1.0,0.0,0.0,1.0,7.0,1.0,0,0